version: 2.1

jobs:
  test:
    machine: true
    steps:
      - checkout
      - run:
          name: "Bring up docker"
          command: "docker-compose up -d"
      - run:
          name: "Composer install"
          command: "docker-compose exec php composer install"
      - run: 
          name: "Run unit tests"
          command: "docker-compose exec php ./vendor/bin/phpunit

workflows:
  test-workflow:
    jobs:
      - test
